New error fixes
- NoSuchFieldException on Android 6.0
- NoClassDefFoundError on A2.3
- Calendar problem caused by Android Support Library 22.1

Version bump 2.1.0.4